# Generated by Django 5.0.6 on 2024-07-23 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_apialunos_delete_academyapi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiAluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[django.core.validators.MinLengthValidator(3)],
                        verbose_name="nome",
                    ),
                ),
                (
                    "lastname",
                    models.CharField(max_length=100, verbose_name="sobrenome"),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        validators=[django.core.validators.MinLengthValidator(11)],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de criação"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="data de vencimento"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ApiAlunos",
        ),
    ]
