# Generated by Django 5.0.6 on 2024-07-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_apialuno_delete_apialunos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apialuno",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="data de vencimento"
            ),
        ),
    ]
