# Generated by Django 5.0.6 on 2024-07-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_apialuno_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apialuno",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
