# Generated by Django 5.0.6 on 2024-08-12 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_apialuno_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="apialuno",
            name="phone_number",
            field=models.CharField(
                default="",
                max_length=11,
                validators=[django.core.validators.MinLengthValidator(11)],
            ),
        ),
    ]
